```plantuml
@startuml usecaseDiagram
    actor User


    User --> (Register Account)
    User --> (Log In)


    User --> (Create Fitness Log)
    User --> (View Fitness Logs)
    User --> (Update Fitness Log)
    User --> (Delete Fitness Log)


    User --> (View Analytics)


    (View Analytics) ..> (Calculate Summaries) : include
    (View Analytics) ..> (Generate Charts) : include
@enduml
```
